service_id = 2

[database]
host = "shorekeeper-postgres:5432"
user_name = "shorekeeper_user"
password = "shorekeeper_pass"
db_name = "shorekeeper_db"

[service_end_point]
addr = "tcp://0.0.0.0:10004"

[gateway_end_point]
addr = "tcp://shorekeeper-gateway-server:10003"
