service_id = 1

[network]
kcp_port = 7777

[protokey]
builtin_encryption_msg_id = [111, 112]
use_client_key = true

[service_end_point]
addr = "tcp://0.0.0.0:10003"

[game_server_end_point]
addr = "tcp://shorekeeper-game-server:10004"

[database]
host = "shorekeeper-postgres:5432"
user_name = "shorekeeper_user"
password = "shorekeeper_pass"
db_name = "shorekeeper_db"
