[network]
http_addr = "0.0.0.0:5500"

[gateway]
host = "host.docker.internal"
port = 7777

[database]
host = "shorekeeper-postgres:5432"
user_name = "shorekeeper_user"
password = "shorekeeper_pass"
db_name = "shorekeeper_db"
